name: wiki
channels:
  - conda-forge
dependencies:
  - python=3.11
  - requests
  - jupyterlab
  - ipykernel
  - structlog
  - tqdm
  - pip
  - numpy
  - pandas
  - datasets
  - mypy
  - black[jupyter]
  - flake8
  - pre-commit
  - pytest
  - pyyaml
  - pip:
    - wikipedia-API
    - -e .
